.changeset/popular-bears-invite.md
packages/core/src/client.ts
packages/core/src/types/converters.ts
packages/core/src/types/unified.ts

This PR adds ability for core to specify chain IDs in the chains and assets requests

[Core] Chains and Assets Filtering

---

examples/nextjs/pages/index.tsx
examples/nextjs/pages/web-component.tsx

Move web-component example to separate page "/web-component"

Move web-component example to separate page

---

.changeset/funny-stingrays-hug.md
packages/widget/README.md

Update widget README

---

.changeset/moody-drinks-brush.md
packages/core/src/types/__test__/converters.test.ts
packages/core/src/types/converters.ts
packages/core/src/types/unified.ts

Updates route response types to add estimate route durations

add estimated_route_duration_seconds to route responses

---

.changeset/rich-fishes-lie.md
.changeset/young-seals-repeat.md
examples/nextjs/pages/provider.tsx
examples/nextjs/styles/globals.css
packages/widget/src/index.ts
packages/widget/src/ui/index.tsx

Add `SwapWidgetWithoutProviders`

Swap widget without providers

---

.changeset/spicy-doors-cry.md
packages/widget/src/ui/AssetSelect/AssetSelectContent.tsx
packages/widget/src/ui/ChainSelect/ChainSelectContent.tsx

Fix auto focusing input field in shadow-dom

[FRE-873] Fix auto focusing input field in shadow-dom

---

.changeset/honest-rings-sort.md
packages/widget/package.json
packages/widget/src/ui/WithStyledShadowDom.tsx
yarn.lock

Let's go back to using `react-shadow-scope` since it didn't have any issues with providers

Fix provider issue by using react-shadow-scope

---

.changeset/shy-dragons-stare.md
docs/widget/configuration-options.mdx
examples/nextjs/pages/provider.tsx
packages/widget/README.md
packages/widget/src/hooks/use-swap-widget.ts
packages/widget/src/ui/PreviewRoute/SetAddressDialog.tsx
packages/widget/src/ui/Widget.tsx
packages/widget/src/ui/index.tsx

Add persistSwapWidgetState prop, which is true by default
Add example in /provider of disabling it
https://github.com/user-attachments/assets/117a8c34-2a3b-438c-b97b-7f012b8f1160

[FRE 876] Add persistSwapWidgetState prop

---

.github/workflows/publish.yml

Found someone else wanting to do something similar:
https://github.com/changesets/action/issues/50#issuecomment-851522508

Update automerge label workflow

---

.changeset/six-comics-turn.md
packages/widget/src/hooks/use-make-wallets.tsx
packages/widget/src/hooks/use-swap-widget.ts
packages/widget/src/ui/PreviewRoute/SetAddressDialog.tsx
packages/widget/src/ui/WalletModal/PraxWalletIndex.tsx
packages/widget/src/ui/Widget.tsx

this PR extends the get address function to have a source chain id parameter.
There will be another PR for getting the penumbra compat address after this release

fix: noble to penumbra prax wallet

---

.changeset/pretty-eggs-warn.md
packages/widget/src/ui/PreviewRoute/make-chain-ids-with-actions.ts

Find last swapAction that meets criteria in makeChainIdsWithActions

---

.changeset/twelve-dancers-fold.md
packages/widget/src/ui/PreviewRoute/SetAddressDialog.tsx

Use monospace font for address input

---

docs/widget/configuration-options.mdx
docs/widget/getting-started.mdx
docs/widget/web-component.mdx
examples/nextjs/pages/provider.tsx
packages/widget/README.md
packages/widget/src/hooks/use-make-wallets.tsx
packages/widget/src/store/callbacks.ts
packages/widget/src/ui/PreviewRoute/index.tsx
packages/widget/src/ui/index.tsx

https://github.com/user-attachments/assets/e8ce9c4b-097b-4fbc-ac78-92df456bab57

Add callbacks

---

.changeset/giant-geckos-switch.md
packages/client/src/client.ts

[FRE-913] feat: erc20 approval set to required approval amount

---

.changeset/funny-apes-doubt.md

Follow up to https://github.com/skip-mev/skip-go/pull/161 to bump changeset for widget

Add changeset to widget

---

examples/nextjs/package.json
examples/nextjs/pages/inject-wallet.tsx
packages/widget/src/hooks/use-account.ts
packages/widget/src/hooks/use-auto-set-address.ts
packages/widget/src/hooks/use-skip-client.ts
packages/widget/src/provider/index.tsx
packages/widget/src/provider/skip-provider.tsx
packages/widget/src/ui/PreviewRoute/ChainStep.tsx
packages/widget/src/ui/PreviewRoute/types.ts
yarn.lock

feat: inject wallet from parent

---

.changeset/many-paws-drop.md
.changeset/popular-beans-fix.md
docs/swagger.yml
packages/client/src/types/converters.ts
packages/client/src/types/shared.ts

Add fee_payment_address and fee_denom fields to SmartRelayFeeQuote object

smart relay fee quote field changes

---

.github/workflows/publish.yml
packages/widget/package.json

Add publish script to release workflow

Add publish script to release workflow

---

.changeset/empty-bears-travel.md
examples/nextjs/pages/index.tsx
examples/nextjs/pages/provider.tsx
packages/widget/src/hooks/use-swap-widget.ts

Fix filter + defaultRoute bug

---

.changeset/sharp-jokes-hammer.md
packages/widget/src/store/disclosures.ts

old:
https://github.com/user-attachments/assets/73fa726a-acff-42bc-ba4a-43dd0c6368b7
new:
https://github.com/user-attachments/assets/55849623-0c45-492b-ba55-9307d3c39c3e

Remove scrollStore and scrollTop behavior in disclosures

---

.changeset/chilled-books-grow.md
packages/widget/src/ui/SwapDetails.tsx

Fix price calculation to include bridging fees

---

.changeset/good-coats-type.md
packages/client/src/types/__test__/converters.test.ts
packages/client/src/types/converters.ts
packages/client/src/types/shared.ts

Adds an estimated amount out field to the `SwapExactIn` and `SmartSwapExactIn` operations

add estimated amount out to swap operations

---

packages/widget-v2/src/modals/ManualAddressModal/ManualAddressModal.tsx
packages/widget-v2/src/modals/ManualAddressModal/isValidWalletAddress.ts

Add wallet address validation logic, pretty much exactly the same as widget v1, but with a separate function and using switch

Add wallet address validation

---

packages/widget-v2/eslint.config.mjs
packages/widget-v2/src/state/skipClient.ts
packages/widget-v2/src/utils/atomWithDebounce.ts

Add debouncing route request using atomWithDebounce
https://jotai.org/docs/recipes/atom-with-debounce
Add eslint rule to enforce semicolons

Add debouncing route request

---

.changeset/bright-rules-hear.md
packages/widget/src/ui/HistoryDialog/HistoryList.tsx
packages/widget/src/ui/PreviewRoute/index.tsx

feat: adjust estimated time text

---

packages/widget-v2/src/components/ModalRowItem.tsx
packages/widget-v2/src/components/VirtualList.tsx

https://github.com/user-attachments/assets/977ddc74-d1f9-497f-88e3-c79e653f074b

Add keyboard navigation to VirtualList

---

docs/swagger.yml

Updated API ref example names formatting for consistency

fix: api reference example names for consistency 

---

packages/widget-v2/src/icons/SpinnerIcon.tsx
packages/widget-v2/src/pages/SwapPage/ConnectedWalletContent.tsx
packages/widget-v2/src/pages/SwapPage/SwapPage.tsx
packages/widget-v2/src/pages/SwapPage/useSetMaxAmount.ts
packages/widget-v2/src/pages/SwapPage/useSourceBalance.ts

https://github.com/user-attachments/assets/0c173f58-28a8-4ff0-a30b-3d542c606a67

feat(widget-v2)/balance loading state

---

packages/widget-v2/src/modals/TokenAndChainSelectorModal/TokenAndChainSelectorModal.tsx
packages/widget-v2/src/modals/TokenAndChainSelectorModal/TokenAndChainSelectorModalRowItem.tsx
packages/widget-v2/src/modals/TokenAndChainSelectorModal/TokenAndChainSelectorModalSearchInput.tsx

Feat(widget v2)/summary grouping assets balance

---

packages/widget-v2/package.json
yarn.lock

bump graz to 0.1.25

---

.changeset/proud-rice-smoke.md
packages/client/src/client-types.ts
packages/client/src/client.ts
packages/widget-v2/src/hooks/useCreateCosmosWallets.tsx
packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPage.tsx
packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPageRouteSimpleRow.tsx
packages/widget-v2/src/providers/CosmosProvider.tsx
packages/widget-v2/src/state/swapExecutionPage.ts

https://github.com/user-attachments/assets/a4139923-57de-4760-b1c1-de0915dc5747

[FRE-1011, FRE-1012] feat: onTransactionSigned and onValidateGasBalance

---

packages/widget-v2/src/pages/SwapPage/SwapPageAssetChainInput.tsx
packages/widget-v2/src/utils/misc.tsx

return initial value if no value found in localStorage
get rid of "--" if no usdValue is found

return initial value if no value found in localStorage

---

packages/widget-v2/src/components/MainButton.tsx
packages/widget-v2/src/components/Typography.tsx
packages/widget-v2/src/pages/ErrorPage/ErrorPageUnexpected.tsx
packages/widget-v2/src/pages/SwapPage/SwapPage.tsx
packages/widget-v2/src/pages/SwapPage/SwapPageAssetChainInput.tsx

Add nice error messages for sourceAsset/destination asset/amount undefined
Change text to say "select asset" to match other terminology 
https://github.com/user-attachments/assets/632d58a6-fcfe-44ac-82fa-dd287f4e7650

[FRE-1048] Add nice error messages for sourceAsset/destination asset/amount undefined

---

packages/widget-v2/src/components/Modal.tsx

https://github.com/user-attachments/assets/665805b5-a297-4fff-932e-8fed4065f081

[FRE-1068, FRE-1069] add modal animation

---

packages/widget-v2/src/components/RenderWalletList.tsx
packages/widget-v2/src/constants/graz.ts
packages/widget-v2/src/hooks/useCreateCosmosWallets.tsx
packages/widget-v2/src/hooks/useCreateEvmWallets.tsx
packages/widget-v2/src/hooks/useCreateSolanaWallets.tsx
packages/widget-v2/src/hooks/useGetAccount.ts
packages/widget-v2/src/hooks/useWalletList.tsx
packages/widget-v2/src/modals/ConnectedWalletModal/ConnectedWalletModal.tsx
packages/widget-v2/src/modals/SetAddressModal/SetAddressModal.tsx
packages/widget-v2/src/modals/WalletSelectorModal/WalletSelectorModal.tsx
packages/widget-v2/src/pages/SwapPage/SwapPage.tsx
packages/widget-v2/src/state/chains.ts
packages/widget-v2/src/state/wallets.ts

https://github.com/user-attachments/assets/17849e2d-01b1-4fd4-bb99-3e8154e1a533

[FRE-1021 FRE-1054] feat: connect eco

---

packages/widget-v2/src/components/Modal.tsx

https://github.com/user-attachments/assets/539025b3-a080-423b-8fd9-21d70fd0bdcc

Speed up animation of modal/drawer

---

packages/widget-v2/src/hooks/useFetchAllBalances.ts
packages/widget-v2/src/pages/SwapPage/ConnectedWalletContent.tsx
packages/widget-v2/src/pages/SwapPage/SwapPage.tsx

[FRE-1132, FRE-1133] feat: get all balances in evm chains

---

packages/widget-v2/src/pages/SwapPage/SwapPage.tsx

Only render "please enter a valid amount" if both input fields are falsy

---

packages/widget-v2/src/components/Typography.tsx
packages/widget-v2/src/pages/ErrorPage/ErrorPageAuthFailed.tsx
packages/widget-v2/src/pages/ErrorPage/ErrorPageContent.tsx
packages/widget-v2/src/pages/ErrorPage/ErrorPageTimeout.tsx
packages/widget-v2/src/pages/ErrorPage/ErrorPageTradeAdditionalSingingRequired.tsx
packages/widget-v2/src/pages/ErrorPage/ErrorPageTradeWarning.tsx
packages/widget-v2/src/pages/ErrorPage/ErrorPageTransactionFailed.tsx
packages/widget-v2/src/pages/ErrorPage/ErrorPageTransactionReverted.tsx
packages/widget-v2/src/pages/ErrorPage/ErrorPageUnexpected.tsx
packages/widget-v2/src/pages/SwapPage/SwapPage.tsx
packages/widget-v2/src/utils/number.ts

Updated `calculatePercentageDifference` function name to be `calculatePercentageChange`
Updated `SwapPage` to use `calculatePercentageChange`

Update SwapPage to use calculatePercentageChange from @/utils/number to be consistent

---

packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPage.tsx
packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailed.tsx
packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailedRow.tsx
packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPageRouteSimple.tsx
packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPageRouteSimpleRow.tsx

Add edit destination wallet to detailed route page

---

packages/widget-v2/src/hooks/useGetAssetDetails.tsx
packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPageRouteSimpleRow.tsx
packages/widget-v2/src/pages/SwapPage/SwapPage.tsx
packages/widget-v2/src/pages/SwapPage/SwapPageAssetChainInput.tsx
packages/widget-v2/src/pages/TransactionHistoryPage/TransactionHistoryPage.tsx
packages/widget-v2/src/pages/TransactionHistoryPage/TransactionHistoryPageHistoryItem.tsx
packages/widget-v2/src/state/history.ts
packages/widget-v2/src/utils/number.ts

1. dynamic font size resizing and per-asset decimal place validation in inputs
2. only show history button if history available
3. update ui immediately (not just local storage) when history item is deleted from history page

[FRE-1084, FRE-1171, FRE-1170] 

---

packages/widget-v2/src/devMode/loadWidget.tsx
packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPage.tsx
packages/widget-v2/src/state/swapPage.ts
packages/widget-v2/src/widget/Widget.tsx

[FRE-1161]

---

packages/widget-v2/src/hooks/useGetSourceBalance.ts
packages/widget-v2/src/pages/SwapPage/ConnectedWalletContent.tsx
packages/widget-v2/src/providers/CosmosProvider.tsx

- Fix 0 balance
- Fix undefined symbol
- Disable autoreconnect in GrazProvider

Fix 0 balance, fix undefined symbol

---

packages/widget-v2/src/pages/ErrorPage/ErrorPageTransactionFailed.tsx
packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailed.tsx
packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPageRouteSimpleRow.tsx
packages/widget-v2/src/pages/SwapPage/SwapDetailModal.tsx
packages/widget-v2/src/stories/ErrorState.stories.tsx
packages/widget-v2/src/utils/number.ts

Left in EVMDisclaimer component code because I feel it'll likely be useful in the future. open to removing it as well.

[FRE-1183, FRE-1185, FRE-1146]

---

packages/widget-v2/src/widget/Widget.tsx

I honestly doubt this prop is going to be used much or even at all, but I want to be consistent on the naming

Update swapVenues chainID -> chainId

---

packages/widget-v2/src/widget/Widget.tsx

handle apiURL -> apiUrl

---

packages/widget-v2/src/pages/SwapPage/SlippageSelector.tsx
packages/widget-v2/src/pages/SwapPage/SwapDetailModal.tsx
packages/widget-v2/src/state/swapPage.ts
packages/widget-v2/src/utils/route.ts

also externalized fee type checking logic and refactor slippage logic as its own component

[FRE-1181] fix: custom swap settings ux behavior

---

packages/widget/package.json
packages/widget/src/widget/Widget.tsx
packages/widget/web-component/package.json

Update chainIdsToAffiliates prop to be camelCase
Unrelated but also updated web-component publish script to remove alpha tag and bumped version to match widget

[FRE-1212] Update chainIdsToAffiliates prop to be camelCase, update web-component publish script/version

---

.changeset/tough-ravens-begin.md
packages/widget/src/components/Modal.tsx
packages/widget/src/modals/SwapSettingsDrawer/SwapSettingsDrawer.tsx

Fix light mode modals 

---

.changeset/moody-ghosts-invent.md
examples/nextjs/pages/index.tsx
packages/widget/src/components/Typography.tsx
packages/widget/src/devMode/loadWidget.tsx
packages/widget/src/icons/HistoryArrowIcon.tsx
packages/widget/src/modals/SwapSettingsDrawer/SwapSettingsDrawer.tsx
packages/widget/src/pages/SwapPage/SlippageSelector.tsx
packages/widget/src/pages/TransactionHistoryPage/TransactionHistoryPage.tsx
packages/widget/src/pages/TransactionHistoryPage/TransactionHistoryPageHistoryItem.tsx
packages/widget/src/pages/TransactionHistoryPage/TransactionHistoryPageHistoryItemDetails.tsx
packages/widget/src/utils/date.ts
packages/widget/src/widget/Widget.tsx

Add mobile slippage settings
Add mobile history page

Add mobile styling for history page and settings drawer

---

.changeset/great-buckets-lay.md
packages/widget/src/components/ModalHeader.tsx
packages/widget/src/components/VirtualList.tsx
packages/widget/src/hooks/useIsMobileScreenSize.ts
packages/widget/src/modals/AssetAndChainSelectorModal/AssetAndChainSelectorModal.tsx
packages/widget/src/modals/AssetAndChainSelectorModal/AssetAndChainSelectorModalSearchInput.tsx
packages/widget/src/pages/SwapExecutionPage/SwapExecutionPage.tsx
packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailedRow.tsx
packages/widget/src/pages/TransactionHistoryPage/TransactionHistoryPage.tsx
packages/widget/src/pages/TransactionHistoryPage/TransactionHistoryPageHistoryItem.tsx

also removed trailing zeroes from certain amounts to leave more space on the UI

[FRE-1236, FRE-1232, FRE-1231, FRE-1229] 

---

.changeset/curvy-dolphins-suffer.md
packages/widget/src/components/MainButton.tsx

Replace jank spinning pulse with linear loading pulse
https://github.com/user-attachments/assets/adadca72-6c7e-4233-8c2b-8855341ee1a9
https://github.com/user-attachments/assets/6148d885-5a8f-455a-ab17-bcb7dfa681be

Linear loading pulse border animation instead of non-linear rotating anim

---

.changeset/fresh-zebras-pump.md
packages/widget/src/components/VirtualList.tsx
packages/widget/src/pages/TransactionHistoryPage/TransactionHistoryPage.tsx

[FRE-1237] feat: fix transaction history modal height

---

.changeset/perfect-bats-grow.md
packages/widget/src/hooks/useGetSourceBalance.ts
packages/widget/src/pages/ErrorPage/ErrorPageTradeWarning.tsx
packages/widget/src/pages/SwapPage/ConnectedWalletContent.tsx
packages/widget/src/utils/number.ts

also remove confusing tildas from error ouput

[FRE-1247, FRE-1293] fix: improve balance loading state handling and display

---

.changeset/sweet-garlics-crash.md
package.json
packages/widget/package.json
yarn.lock

https://github.com/graz-sh/graz/pull/180

fix: android signing not opening wallet

---

.changeset/cool-boats-attack.md
packages/widget/src/devMode/loadWidget.tsx
packages/widget/src/state/route.ts
packages/widget/src/state/swapExecutionPage.ts
packages/widget/src/state/swapPage.ts

[FRE-1370] Fix route preference selector

---

.changeset/wicked-beans-judge.md
packages/widget/src/pages/SwapExecutionPage/useBroadcastedTxs.ts

Track error in sentry if the transaction fails

[FRE-1382] Track error in sentry if the transaction fails

---

.changeset/tender-llamas-matter.md
packages/widget/src/components/GroupedAssetImage.tsx
packages/widget/src/modals/AssetAndChainSelectorModal/AssetAndChainSelectorModalRowItem.tsx
packages/widget/src/pages/SwapPage/SwapPage.tsx
packages/widget/src/pages/SwapPage/SwapPageAssetChainInput.tsx

Add GroupedAssetImage component to more elegantly handle loading grouped asset images

[FRE-1366] Add GroupedAssetImage component to more elegantly handle loading Asset images

---

.changeset/thick-fishes-explode.md
packages/widget/src/components/Layout.tsx
packages/widget/src/components/MainButton.tsx
packages/widget/src/icons/BridgeArrowIcon.tsx
packages/widget/src/icons/BridgeIcon.tsx
packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteSimpleRow.tsx
packages/widget/src/pages/SwapPage/ConnectedWalletContent.tsx
packages/widget/src/pages/SwapPage/SwapPageAssetChainInput.tsx
packages/widget/src/pages/SwapPage/SwapPageBridge.tsx

Mobile styling updates

---

.changeset/cold-walls-bow.md
packages/widget/src/index.tsx

i really dont know if this will fix it xd

Filter out non-error or fatal level events from sentry

---

docs/widget/configuration.mdx

Fixes 2 broken links in docs in the route config section for the widget

Fix Broken Links in Docs

---

.changeset/few-bobcats-tan.md
docs/widget/configuration.mdx
packages/widget/src/components/ModalHeader.tsx
packages/widget/src/components/RenderWalletList.tsx
packages/widget/src/pages/TransactionHistoryPage/TransactionHistoryPage.tsx

Also add min-height to history page (for mobile, this isn't an issue on desktop)
new:
old:

Fix connect wallet styling

---

.changeset/lazy-adults-train.md
packages/widget/src/state/swapPage.ts
packages/widget/src/utils/atomWithDebounce.ts

Add ability to set default for debounced values

Fix bug with pulsing input

---

.changeset/hot-cougars-sip.md
packages/widget/src/state/skipClient.ts

initial load/fetch is not using the apiUrl passed from param, my proposed solution is to make the apiUrl to be the query key

fix apiUrl not changed

---

.changeset/gold-dots-notice.md
packages/widget/src/components/Layout.tsx
packages/widget/src/hooks/useIsMobileScreenSize.ts
packages/widget/src/modals/AssetAndChainSelectorModal/AssetAndChainSelectorModalRowItem.tsx

Update mobile Asset/Chain selector modal to avoid word wrapping with small screen widths

---

.changeset/warm-doors-obey.md
packages/widget/src/components/GroupedAssetImage.tsx
packages/widget/src/components/MainButton.tsx
packages/widget/src/modals/AssetAndChainSelectorModal/AssetAndChainSelectorModal.tsx
packages/widget/src/modals/AssetAndChainSelectorModal/AssetAndChainSelectorModalSearchInput.tsx
packages/widget/src/state/route.ts

reduced font size so mobile can fit 3 lines
fixed this img url issue

[FRE-1451] Enhance asset handling in GroupedAssetImage 

---

.changeset/dry-roses-punch.md
packages/widget/src/hooks/useAutoSetAddress.ts

fix bug with evm recovery address not working on mobile

---

.changeset/stupid-drinks-tap.md
packages/widget/src/pages/ErrorPage/ErrorPageGoFastWarning.tsx
packages/widget/src/pages/ErrorPage/ErrorPageUnexpected.tsx
packages/widget/src/state/swapExecutionPage.ts
packages/widget/src/widget/initSentry.ts

add these tags to sentry:
- goFastWarning
- errorMessage
- txCompleted

Add 3 tags to sentry

---

packages/widget/src/hooks/useSettingsDrawer.tsx
packages/widget/src/pages/ErrorPage/ErrorPageGoFastWarning.tsx
packages/widget/src/pages/SwapPage/SwapPage.tsx

Fixed version:
https://github.com/user-attachments/assets/04640e3b-4b60-4c90-a3bd-952ecbe0d9ca
Previous version:
https://github.com/user-attachments/assets/a14a1d37-09ee-465b-b690-43f7cf15b3b7

Simplify useSettingsDrawer to only return Footer element and drawerOpen

---

.changeset/khaki-rules-marry.md
packages/widget/src/components/ModalRowItem.tsx
packages/widget/src/modals/AssetAndChainSelectorModal/AssetAndChainSelectorModal.tsx
packages/widget/src/modals/AssetAndChainSelectorModal/AssetAndChainSelectorModalRowItem.tsx

Reduce gap between AssetAndChainSelectorModalRowItems

---

.changeset/rude-doors-deny.md
packages/widget/src/pages/SwapExecutionPage/SwapExecutionButton.tsx
packages/widget/src/pages/SwapExecutionPage/SwapExecutionPage.tsx
packages/widget/src/pages/SwapExecutionPage/useCountdown.ts
packages/widget/src/utils/countdownTimer.ts
packages/widget/src/utils/number.ts

https://github.com/user-attachments/assets/8b0f4a64-82ed-4b41-86eb-4ca898e1e634

Add countdownTimer

---

.changeset/famous-cats-smoke.md
packages/widget/src/components/GoFastSymbol.tsx
packages/widget/src/components/ModalHeader.tsx
packages/widget/src/components/Tooltip.tsx
packages/widget/src/hooks/useCopyAddress.ts
packages/widget/src/modals/ConnectedWalletModal/ConnectedWalletModal.tsx
packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailed.tsx
packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailedRow.tsx
packages/widget/src/pages/SwapPage/ConnectedWalletContent.tsx
packages/widget/src/pages/SwapPage/RoutePreferenceSelector.tsx
packages/widget/src/pages/SwapPage/SlippageSelector.tsx

lol the stretching xd
https://github.com/user-attachments/assets/a39446e3-954f-42a0-8896-06ae6fc1257e

Add Tooltip component, Copy to clipboard UI feedback

---

docs/eureka/devnet-testing-guide.mdx

DOCS:
This PR updates the docs to align with the changes to the README of the CLI tool, ahead of stripping out the CLI README so that these docs become the source of truth.

docs: sync to cli README, add transfer back commands, cleaning

---

docs/eureka/devnet-testing-guide.mdx

1. Add a contact us section
2. fix some title naming changes
3. explain the diff of denom usage on cosmos to ethereum

Small Updates To Eureka Devnet Guide

---

.changeset/small-maps-wash.md
packages/widget/src/modals/AssetAndChainSelectorModal/AssetAndChainSelectorModal.tsx

https://github.com/user-attachments/assets/9770d0f7-7a1f-41a6-95b0-a6f3bc44dba0

Add ability to select asset/chain by pressing enter when only one option is left

---

docs/eureka/devnet-testing-guide.mdx

Change for clarity flow for CLI walkthrough.

docs: fix: change checkout<>cd ordering for instructions to fix flow

---

.changeset/eleven-hairs-camp.md
packages/widget/src/hooks/useCreateEvmWallets.tsx
packages/widget/src/hooks/useTxHistory.ts
packages/widget/src/pages/TransactionHistoryPage/TransactionHistoryPageHistoryItem.tsx
packages/widget/src/pages/TransactionHistoryPage/TransactionHistoryPageHistoryItemDetails.tsx

Update Tx history to show all tx links

---

.changeset/hip-eggs-compare.md
examples/nextjs/src/app/page.tsx
packages/widget/src/devMode/loadWidget.tsx
packages/widget/src/index.tsx
packages/widget/src/state/route.ts
packages/widget/src/state/swapPage.ts
packages/widget/src/widget/Widget.tsx

- Add `resetWidget` function
- Update `initializeDebounceValuesEffect` and `isWaitingForNewRouteAtom`

Add resetWidget function

---

.changeset/selfish-months-jog.md
packages/widget/src/components/MainButton.tsx
packages/widget/src/components/Typography.tsx
packages/widget/src/pages/SwapPage/SwapPageAssetChainInput.tsx

Update to use correct text color in main button when button is disabled
Update font weight to 400 (differs from design spec but looks more similar to the design)
design:

[FRE-1440] Main button styling update

---

packages/widget/src/hooks/useCreateCosmosWallets.tsx

The Noble team released a fix in their software (`v9.0.1`: https://github.com/noble-assets/noble/releases/tag/v9.0.1) which fixes bech32m validation, thus making transparent addresses unnecessary. 
This PR restores ephemeral addresses usage for `noble-1` since the software fix was deployed successfully.

widget: use ephemeral addresses for penumbra

---

.changeset/sixty-melons-count.md
packages/widget/src/components/ModalHeader.tsx
packages/widget/src/hooks/useIsMobileScreenSize.ts

Fixes flickering on mobile styling
https://github.com/user-attachments/assets/cd8648ff-2a3d-491f-acdc-3d16dfd48ebb

Fix useIsMobileScreenSize styling flickering / defaulting to desktop causing flickering on mobile

---

.changeset/silly-jars-hope.md
packages/widget/src/pages/SwapExecutionPage/SwapExecutionPage.tsx
packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailed.tsx
packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailedRow.tsx
packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteSimple.tsx

https://github.com/user-attachments/assets/125b1663-c651-4dfb-b95c-327e6a2cdbbb

[FRE-1519] Simplify loading states, fix loading spinners sometimes being out of sync

---

.changeset/soft-actors-join.md
examples/nextjs/src/app/page.tsx
examples/nextjs/src/hooks/useURLQueryParams.tsx
packages/widget/src/state/skipClient.ts
packages/widget/src/widget/useInitWidget.ts

- Fix testnet causing widget to double fetch api requests
- wait for testnet and apiURL to be set by useInitWidget before enabling api requests

Fix testnet causing widget to double fetch api requests 

---

.changeset/stupid-bananas-occur.md
packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteSimpleRow.tsx

Add address copied to simple view

---

.changeset/old-lobsters-fix.md
packages/widget/src/hooks/useAutoSetAddress.ts
packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailedRow.tsx

Styling updates to detailed route view

---

.changeset/itchy-experts-explain.md
packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailedRow.tsx
packages/widget/src/pages/SwapExecutionPage/useSyncTxStatus.tsx

left align address text in detailed view

---

.changeset/ten-tips-ring.md

Add changeset for this PR https://github.com/skip-mev/skip-go/pull/942

Add changeset for rootId PR

---

.changeset/long-bulldogs-vanish.md
packages/client/src/types/converters.ts
packages/client/src/types/shared.ts

Adds to_chain_entry_contract_address to both Eureka Transfer and Transfer types, incl the converters

Add to_chain_entry_contract_address

---

.changeset/silly-zoos-relax.md
packages/widget/src/components/ModalRowItem.tsx
packages/widget/src/devMode/global.css
packages/widget/src/devMode/loadWidget.tsx
packages/widget/src/modals/AssetAndChainSelectorModal/AssetAndChainSelectorModal.tsx
packages/widget/src/modals/AssetAndChainSelectorModal/AssetAndChainSelectorModalRowItem.tsx
packages/widget/src/modals/AssetAndChainSelectorModal/AssetAndChainSelectorModalSearchInput.tsx
packages/widget/src/modals/AssetAndChainSelectorModal/useFilteredAssets.ts
packages/widget/src/modals/AssetAndChainSelectorModal/useFilteredChains.ts
packages/widget/src/pages/SwapPage/SwapPageAssetChainInput.tsx
packages/widget/src/pages/SwapPage/SwapPageFooter.tsx
packages/widget/src/state/assetSymbolsSortedToTop.ts
packages/widget/src/state/ibcEurekaHighlightedAssets.ts
packages/widget/src/widget/Widget.tsx
packages/widget/src/widget/useInitWidget.ts

- Updated sorting logic
- Updated chains sorting to prioritize the one with the symbol contained within the chainName
- Added eureka highlighting
- Added ibcEurekaHighlightedAssets prop
- Added assetSymbolsSortedToTopAtom
ibcEurekaHighlightedAssets
dark | light
--- | ---
test whilelabing/removing logo with data-logo attribute
chain sorting prioritizes the one with the symbol contained within the chainName

Add Eureka styling and sorting

---

.changeset/sweet-tables-mate.md
packages/client/src/client.ts

Add testnet sepolia to bypass gas

---

.changeset/little-zoos-worry.md
examples/nextjs/src/app/page.tsx
packages/widget/src/index.tsx
packages/widget/src/modals/AssetAndChainSelectorModal/AssetAndChainSelectorModal.tsx
packages/widget/src/pages/SwapPage/SwapPage.tsx

this will be used in the studio

Export asset and chain selector modal to be useable outside the widget

---

.changeset/tough-cars-sell.md
packages/widget/src/modals/AssetAndChainSelectorModal/useFilteredChains.ts

Fix sorting with eureka highlighting to not return anything if both assets are highlighted

---

packages/widget/src/icons/BridgeArrowIcon.tsx

Fix warning in dev

---

docs/client/migration-guide.mdx
docs/release-notes/api.mdx
docs/release-notes/client.mdx
docs/release-notes/widget.mdx

Update release notes for API, client library, and widget;

[API-4122] Update release notes for API, client library, and widget; 

---

.changeset/three-chicken-hope.md
packages/widget/src/components/Modal.tsx
packages/widget/src/pages/SwapPage/SwapPage.tsx

Add fix for windows after-image 
https://github.com/user-attachments/assets/2b3bea32-61f7-4ce2-b134-c0e0015e5db1

Re-add Modal close animation

---

docs/release-notes/api.mdx

This PR adds more detailed documentation to the API release notes including:
- Enhanced fee transparency section with JSON response sample from /v2/fungible/route endpoint
- LayerZero and Stargate integration example showing Widget configuration with experimentalFeatures
- Improved formatting and added link to swagger docs for more endpoint details

Enhance API release notes with detailed examples and code samples

---

packages/client/src/__test__/convert.test.ts

- add tests to ensure `toCamel` and `toSnake` don't mutate inputs
- `yarn test` *(fails: Connect Timeout Error)*

Add immutability tests for convert helpers

---

.changeset/moody-zoos-change.md
packages/widget/src/utils/misc.tsx

- fix removeItem handler in misc utils
- `yarn test` *(fails: Connect Timeout Error)*

Fix localStorage removeItem usage

---

AGENTS.md

- add an AGENTS.md with instructions to create a changeset for every Codex PR
- `git status --short`

Add AGENTS instructions for changesets

---

.changeset/fix-gas-validation.md
packages/client/src/private-functions/validateGasBalances.ts

- fix early return logic in validateGasBalances
- add changeset
- `npm test --silent` *(fails: Error when performing the request to https://repo.yarnpkg.com/...)*

Fix gas balance check

---

.changeset/add-utils-number-tests.md
packages/widget/src/utils/number.test.ts

- add multiple tests for utils/number.ts
- docs: add changeset entry
- `yarn test-widget` *(fails: Couldn't find the node_modules state file)*

Add number utils tests

---

.changeset/chilled-jeans-raise.md
packages/widget/src/pages/SwapExecutionPage/SwapExecutionPage.tsx
packages/widget/src/pages/SwapExecutionPage/useHandleTransactionFailed.tsx
packages/widget/src/pages/SwapPage/SwapPageHeader.tsx
packages/widget/src/pages/TransactionHistoryPage/TransactionHistoryPageHistoryItem.tsx
packages/widget/src/pages/TransactionHistoryPage/TransactionHistoryPageHistoryItemDetails.tsx
packages/widget/src/utils/explorerLink.ts

[FRE-1821] Add link to skip explorer in history page and swapExecutionPage

---

docs/general/fee-info.mdx

Enhance fee-info documentation with details on how bridging fees are applied for EVM and Cosmos source transfers.

 [API-3953] Enhance fee-info documentation

---

.changeset/fast-wombats-play.md
packages/widget/src/utils/crypto.test.ts

- add tests for crypto utility functions
- record changeset
- fix trailing zeros test expectation
- `node .yarn/releases/yarn-3.2.3.cjs workspace @skip-go/widget run test` *(fails: Couldn't find the node_modules state file)*

Add crypto utility tests

---

.changeset/fix-cosmos-wallet-chain-type.md
packages/widget/src/hooks/useCreateCosmosWallets.tsx

- fix chainType for cosmos wallets
- add a changeset
- `npm test` *(fails: Error when performing the request to https://repo.yarnpkg.com/3.2.0/packages/yarnpkg-cli/bin/yarn.js)*

Fix cosmos wallet chain type

---

examples/nuxtjs/app.vue
examples/nuxtjs/package.json
examples/nuxtjs/plugins/skip-widget.client.ts
yarn.lock

Update nuxtjs example 

---

.changeset/few-balloons-battle.md
packages/client/src/private-functions/executeTransactions.ts
packages/client/src/public-functions/waitForTransaction.ts

Add calling track back for svm/evm

---

examples/nextjs/package.json
examples/nextjs/src/app/layout.tsx
examples/nextjs/src/app/page.tsx
examples/nextjs/src/provider/ReactQueryProvider.tsx
yarn.lock

add bridges and venues selection in example

---

.changeset/sweet-nails-rule.md
packages/widget/src/pages/SwapPage/SwapPage.tsx
packages/widget/src/pages/SwapPage/SwapPageAssetChainInput.tsx
packages/widget/src/utils/fees.ts

Add showing "< $0.01 in fees" and "no fees"

---

.changeset/slow-trees-melt.md
packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailedRow.tsx

Add spacing between signature required and and row above in detailed swap view

---

packages/client/src/index.ts
packages/client/src/private-functions/evm/executeEvmTransaction.ts
packages/client/src/private-functions/evm/validateEvmGasBalance.ts
packages/client/src/private-functions/executeTransactions.ts
packages/client/src/private-functions/validateGasBalances.ts
packages/client/src/public-functions/executeMultipleRoutes.ts
packages/client/src/public-functions/executeRoute.ts
packages/client/src/public-functions/subscribeToRouteStatus.ts
packages/widget/src/components/GasOnReceive.tsx
packages/widget/src/components/Layout.tsx
packages/widget/src/hooks/useTxHistory.ts
packages/widget/src/pages/SwapExecutionPage/SwapExecutionPage.tsx
packages/widget/src/pages/TransactionHistoryPage/TransactionHistoryPageHistoryItem.tsx
packages/widget/src/pages/TransactionHistoryPage/TransactionHistoryPageHistoryItemDetails.tsx
packages/widget/src/state/gasOnReceive.ts
packages/widget/src/state/history.ts
packages/widget/src/state/route.ts
packages/widget/src/state/swapExecutionPage.ts

Add status integration for multiple routes

---

packages/widget/src/components/GasOnReceive.tsx

[FRE-2073] update design of GasOnReceive

---

packages/widget/src/state/gasOnReceive.ts

Fix amount in passed to mainRoute being calculated wrong

---

packages/client/src/public-functions/subscribeToRouteStatus.ts
packages/widget/src/components/GasOnReceive.tsx

[FRE-2075] Show transferAssetRelease of failed gasRoutes

---

.changeset/strange-carrots-design.md
packages/client/src/public-functions/subscribeToRouteStatus.ts
packages/widget/src/pages/ErrorWarningPage/UnexpectedErrorPage/UnexpectedErrorPageTransactionReverted.tsx
packages/widget/src/pages/SwapExecutionPage/useHandleTransactionFailed.tsx

[FRE-2092] fix callback

---

.changeset/clean-peas-swim.md
packages/widget/src/components/GroupedAssetImage.tsx

Deprioritize asset images from wormhole

---

apps/explorer/src/components/TransferEventCard.tsx

Only show transferAssetRelease if step !== "Destination"

---

apps/explorer/src/app/page.tsx

fix 2tx routes

---

packages/client/src/utils/clientType.ts

Fix 3tx route crashing page

---

docs/client/gas-on-receive.mdx
docs/docs.json

This PR adds comprehensive documentation for implementing Gas on Receive functionality when building custom frontends with the Skip Go Client Library.
- Created new documentation page at `docs/client/gas-on-receive.mdx`
- Added step-by-step implementation guide with complete code examples
- Included UI component examples and error handling strategies
- Documented best practices and advanced configuration options
- Updated navigation in `docs.json` to include new page in client section
The new guide covers:
- **Gas balance detection** using the `balances` API
- **Route creation** with separate main and gas routes
- **Execution with `executeMultipleRoutes`** including proper slippage settings
- **Complete implementation example** with a `GasOnReceiveManager` class
- **UI components** for …

Add comprehensive Gas on Receive documentation for client library users

---

apps/explorer/src/app/globals.css
apps/explorer/src/app/page.tsx
apps/explorer/src/app/template.tsx
apps/explorer/src/components/Navbar.tsx
apps/explorer/src/components/SearchButton.tsx
apps/explorer/src/components/TokenDetails.tsx
apps/explorer/src/components/TopNav.tsx
apps/explorer/src/components/TransactionDetails.tsx
apps/explorer/src/components/TransferEventCard.tsx
apps/explorer/src/components/TxHashInput.tsx
apps/explorer/src/components/modals/ViewRawDataModal.tsx
apps/explorer/src/mixins/styledScrollbar.ts
packages/widget/src/components/Layout.tsx

https://www.loom.com/share/f847510ff8ed442cad7a22ad40a1481e

[FRE-2155, FRE-2156, FRE-2131, FRE-2134] Refactor search bar and update layout, styling

---

apps/explorer/src/app/page.tsx

Add fake final transfer when 2nd tx status throws an error

---

apps/explorer/src/app/page.tsx
apps/explorer/src/components/ErrorCard.tsx
apps/explorer/src/mixins/styledScrollbar.ts

[FRE-2187, FRE-2200] Update styling of ErrorCard
