.changeset/gentle-trains-tell.md, packages/core/src/__test__/client.test.ts, packages/core/src/client.ts
- This PR changes all /v1/ endpoint calls to use their /v2/ equivalents. This will result in no functionality changes since the endpoints changed have no difference in logic.
=> Migrate to Using V2 Endpoints only

.changeset/happy-ligers-attend.md, README.md, packages/core/README.md, packages/core/package.json, packages/widget/README.md
PR to:
1. update widget to use latest core with v2 endpoints
2. update readmes to use Skip Go language, bumps core version again for readme changes
=> Use latest core for widget, update readmes

.changeset/cool-files-beg.md, examples/nextjs/package.json, examples/nextjs/pages/vue.tsx, packages/widget/src/ui/WebComponent.tsx, yarn.lock
Remove extra `SwapWidgetProvider` wrapping the web-component
Add new example page injecting vue.js in `example/nextjs` at page `/vue`
=> [patch] Fix web components

.changeset/eight-mails-thank.md, examples/nextjs/styles/globals.css, packages/widget/src/styles/cssReset.css, packages/widget/src/ui/Widget.tsx, packages/widget/src/ui/index.tsx
Add CSS reset, checked that it successfully overrides styles from https://test-skip-widget.vercel.app/
updated:
old:
=> [patch] Add css reset

.github/workflows/publish.yml
Add continue-on-error to automerge label to PR step so it doesn't make the Release workflow red if it fails
=> Add continue-on-error to automerge label to PR

.changeset/small-panthers-complain.md, docs/swagger.yml, packages/core/src/__test__/client.test.ts, packages/core/src/types/__test__/converters.test.ts, packages/core/src/types/converters.ts, packages/core/src/types/unified.ts
This adds the new proto field enable_gas_warnings to @skip-go/core
=> [API-3238] Update @skip-go/core to include enable_gas_warnings field

.changeset/odd-cycles-greet.md, docs/widget/configuration-options.mdx, packages/client/src/__test__/client.test.ts, packages/client/src/client-types.ts, packages/client/src/client.ts, packages/widget/src/provider/index.tsx, packages/widget/src/provider/skip-provider.tsx
Add chainIDsToAffiliates to SkipRouterOptions
manually verified that both cumulative_affiliate_bps is passed to /route
and affiliates is passed to /msgs 
Add test for validateChainIDsToAffiliates to validate chainIDsToAffiliates data is not malformed
=> Add chainIDsToAffiliates to SkipRouterOptions, Add chainIDsToAffiliates to SwapWidget props

docs/widget/common-questions.mdx, docs/widget/getting-started.mdx, docs/widget/web-component.mdx, packages/widget/README.md
Add extra info regarding installing peer dependencies to getting-started, web-component and common questions sections in docs
Removed linking to where markdown lives in README, doesn't seem very useful
=> Add Extra info regarding installing peer dependencies to docs

packages/widget-v2/package.json, packages/widget-v2/src/components/AssetChainInput.tsx, packages/widget-v2/src/modals/ManualAddressModal/ManualAddressModal.tsx, packages/widget-v2/src/modals/TokenAndChainSelectorModal/TokenAndChainSelectorModal.tsx, packages/widget-v2/src/modals/TokenAndChainSelectorModal/TokenAndChainSelectorModalRowItem.tsx, packages/widget-v2/src/modals/TransactionHistoryModal/TransactionHistoryModalItem.tsx, packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailedRow.tsx, packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPageRouteSimpleRow.tsx, packages/widget-v2/src/pages/SwapPage/SwapPage.tsx, packages/widget-v2/src/state/chains.ts, packages/widget-v2/src/state/skipClient.ts, packages/widget-v2/src/stories/ManualAddressModals.stories.tsx, packages/widget-v2/src/stories/SwapExecutionPage.stories.tsx, packages/widget-v2/src/utils/useUsdValue.ts, yarn.lock
chain registry is only for cosmos chains, better use chain data from skip api/client.
=> [FRE-951, FRE-952]refactor(widget-v2): remove chain registry usage for chain data

packages/widget/postcss.config.cjs, packages/widget/webpack.config.js
Let's make sure to merge this before the next release goes out 
This PR reverts the change made to postcss.config.cjs in my previous web-components PR
This fixes the build step of @skip-go/widget that was broken due to this change https://github.com/skip-mev/skip-go/pull/192/files#diff-a7f73e7bed85f99a455d8f02c04fee87af5a1186508892f25436cf6788b3ee39L2-L4
=> URGENT Fix @skip-widget postcss config

packages/widget/package.json, packages/widget/src/web-component.tsx, packages/widget/web-component/package.json
apiURL doesn't follow normal camelCase, so for temp solution in widgetv1 we can just manually map it.
alternatives are:
1. renaming apiURL prop as apiUrl in `@skip-go/widget` (force anyone who updates versions to need to update their prop)
2. add a second, duplicate prop apiUrl in `@skip-go/widget`
Also, fix publish script, it should be npm publish instead of npm run publish
=> Fix apiURL prop for web-component

.changeset/two-doors-fold.md, packages/widget-v2/src/hooks/useCreateCosmosWallets.tsx, packages/widget/src/hooks/use-make-wallets.tsx
For any Penumbra account number, a [randomizer](https://buf.build/penumbra-zone/penumbra/docs/9eac98eca7b542929326f69884f35890:penumbra.core.keys.v1#penumbra.core.keys.v1.AddressIndex) can be used to generate an "ephemeral address". These are specifically designed for IBC'ing in. It gives the user what, from the outside looks like a random address, but goes to their choice of accounts.
From within Prax, they can also be pasted into the account verifier and be identified as one of these burner addresses:
There is a specific [view service rpc](https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.view.v1#penumbra.view.v1.EphemeralAddressRequest) that can easily be swapped into the current implementation. You can also see this in current use for …
=> Use penumbra ephemeral address

packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailed.tsx, packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailedRow.tsx, packages/widget-v2/src/pages/SwapExecutionPage/SwapExecutionPageRouteSimpleRow.tsx
Show asset image in swap execution route (instead of chain image)
Show bridge/venue in tooltip
=> Show asset images in detailed rows, add bridge/venue images

packages/widget-v2/src/pages/SwapPage/SwapPageAssetChainInput.tsx, packages/widget-v2/src/state/balances.ts, packages/widget-v2/src/state/swapPage.ts, packages/widget-v2/src/utils/atomWithDebounce.ts
The old logic is super buggy:
the desired behavior is that we should only return `get(destinationAssetAtom)?.amount` on the initial load so I added an atom in `atomWithDebounce` to keep track of the first time that the debounced value gets updated and once it is, we should never return `get(destinationAssetAtom)?.amount` again
=> Fix bug with debouncedValue

packages/widget-v2/src/pages/SwapPage/SwapPageBridge.tsx, packages/widget-v2/src/state/swapPage.ts
it seems to sometimes end up with two of the same asset when inverting swap... i think we need to make a copy of the asset object to fix this.
Also, disable invert swap button while it is spinning
=> Disable invert swap button while spinning, make copy of destination/sourceAsset

packages/widget-v2/src/state/swapExecutionPage.ts, packages/widget-v2/src/state/swapPage.ts, packages/widget-v2/src/utils/misc.tsx
jotai's atomWithStorage by default will be subscribed to storage changes, which means cross-tab sync'd data
https://jotai.org/docs/utilities/storage#parameters
so in order to prevent this, we need to pass in a custom storage implementation:
there are some places where we can keep the cross-tab sync'd data turned on, so i just replaced the problematic ones
=> add atomWithStorageNoCrossTabSync function

packages/widget-v2/src/pages/SwapPage/SwapPageBridge.tsx
This makes SwapExecutionPage match SwapPage properly (height matches exactly) and avoids layout shifting
=> (styling) Set bridge to height=5, align center (vertical align)

packages/widget-v2/src/modals/TokenAndChainSelectorModal/TokenAndChainSelectorModalRowItem.tsx
there's also an issue with INJ on noble-1 not returning decimals and that's the reason the amount rendered is not formatted, which i've reported in slack
new:
old:
=> render totalUsd only if value is > 0

packages/client/src/__test__/client.test.ts, packages/client/src/cache.ts, packages/client/src/client-types.ts, packages/client/src/client.ts, packages/client/src/constants/constants.ts, packages/client/src/transactions.ts, packages/client/src/types/converters.ts, packages/client/src/types/unified.ts
1. implement caching middleware to cache assets and chains calls (configurable with cacheDurationMs and cached based on request options)
2. reduce number of StargateClient instantiations
3. lightly refactor executeTxs to break out chains specific logic into their own functions. 
4. force optimize deps in vite to rebuild skip-go/client to improve testing flow
=> [FRE-1018] speed up time to wallet signing

packages/widget-v2/src/components/MainButton.tsx
=> Fix time estimate wrap

.changeset/afraid-tools-trade.md, .changeset/olive-mice-smell.md, packages/client/src/client.ts, packages/widget/src/constants/skipClientDefault.ts, packages/widget/src/devMode/loadWidget.tsx, packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailed.tsx, packages/widget/src/state/skipClient.ts, packages/widget/src/utils/clientType.ts, packages/widget/src/widget/Widget.tsx
- skip noble-1 validation gas
- fix widget props
- support go fast operation type
=> Support go fast operation type

.changeset/serious-scissors-dance.md, packages/client/package.json, packages/client/src/__test__/client.test.ts, packages/client/src/cache.ts, packages/client/src/create-hash.ts, packages/client/src/crypto-browserify.d.ts, yarn.lock
https://www.npmjs.com/package/create-hash
create-hash is used by crypto-browserify, I figured since we are only using this one function it's overkill to import crypto-browserify
https://www.npmjs.com/package/crypto-browserify
=> [FRE-1290] Use create-hash

.changeset/thick-cherries-provide.md, packages/client/src/types/converters.ts, packages/client/src/types/shared.ts
Renames `send_fee` fields to `messaging_fee` for Stargate transfer operation
=> rename send_fee to messaging_fee

.changeset/clean-weeks-cheer.md, packages/widget/src/widget/ShadowDomAndProviders.tsx
Converting `globalStyles` to a `CSSStyleSheet` object before passing it to `react-shadow-scope` seems to fix this issue (instead of passing it directly as a string/template literal)
https://github.com/jonathandewitt-dev/react-shadow-scope?tab=readme-ov-file#constructed-style-sheets
=> Fix failed to covert value to css stylesheet

.changeset/curvy-suns-study.md, packages/widget/src/index.tsx
This PR manually configures all sentry integrations in order to disable globalHandlers and BrowserApiErrors, because that was triggering the session replay for things that we aren't explicitly trying to record.
https://github.com/getsentry/sentry-javascript/issues/5626#issuecomment-1229931789
List of all integrations:
https://docs.sentry.io/platforms/javascript/configuration/integrations/
=> [FRE-1392] Manually configure integrations to disable globalHandlers and BrowserApiErrors

docs/mint.json
- When using our docs right now the API Reference section doesn't work with localhost links. Mintlify team instructed to add this to resolve the issue.
=> Disable Proxy in Docs

.changeset/red-dots-begin.md, packages/widget/src/components/MainButton.tsx, packages/widget/src/devMode/loadWidget.tsx
Fix disabled main button text color to not use `theme.brandTextColor` prop
=> Fix disabled main button text color

.changeset/violet-dingos-do.md, packages/widget/src/widget/initSentry.ts
thread about issue here -> https://github.com/getsentry/sentry-javascript/issues/7302
I found the workaround in here. The suggested fix using the tunnelRoute option didn't work for me, I suspect because we aren't actually initializing sentry within nextjs but within the widget.
I also checked the difference between compressed and uncompressed data sent from the client and it's around like 30 bytes more per network request, 70bytes vs 100bytes or so
=> Disable replay compression as workaround fix for sentry requests 400'ing

.changeset/hot-chefs-heal.md, packages/widget/src/widget/ShadowDomAndProviders.tsx
=> Update StylesheetManager to wait and target shadowRoot for stylesheet injection

examples/nextjs/package.json, examples/nextjs/src/app/page.tsx, yarn.lock
Adds mobile devtool and remote debugger to nextjs example for mobile testing/debugging
=> Add mobile devtool and remote debugger to nextjs example

package.json, packages/client/src/client.ts, yarn.lock
Trying to make transfers to Penumbra from anyhere in the interchain fails with this error on the main Skip app (not in the widget, curiously):
After digging, I learned that this started after this commit https://github.com/skip-mev/skip-go/commit/8be4ad9b66511041d52d6c27e526934d1f8a55fc added address validation.
The source of the error is that Penumbra uses `bech32m` addresses.
I wish we could stop there, I would have pushed this simple change: https://github.com/skip-mev/skip-go/commit/d512a6e8ea0634c35aa4a7b1ee4aaac99ba034c3 and carried on. Unfortunately, the diff has to be bigger because of interop issues with Noble mainnet.
Some context:
Penumbra addresses contain encrypted metadata. For a variety of reasons, this means that addresses must be encoded using `bech32m`.
1. Noble …
=> Fix address validation to work with Penumbra chains

.changeset/cold-balloons-buy.md, packages/client/src/client.ts, packages/client/src/registry.ts, packages/client/src/stride/index.ts
Fix premature EOF based on the code in stridejs's repo, primarily by replacing `_m0.Reader` by `BinaryWriter` and replacing Long type with bigint
https://github.com/Stride-Labs/stridejs/blob/main/src/parser.ts#L22-L38
https://github.com/Stride-Labs/stridejs/blob/48ba444d2bd1441cb0d47de4b96b3c58ed568ca3/src/codegen/stride/vesting/vesting.ts#L341-L360
=> Fix premature EOF based on the code in stridejs's repo

.changeset/twenty-shrimps-leave.md, packages/widget/src/hooks/useAutoSetAddress.ts, packages/widget/src/hooks/useCreateCosmosWallets.tsx, packages/widget/src/hooks/useCreateEvmWallets.tsx, packages/widget/src/hooks/useCreateSolanaWallets.tsx, packages/widget/src/hooks/useGetAccount.ts, packages/widget/src/hooks/useKeepWalletStateSynced.ts, packages/widget/src/state/wallets.ts, packages/widget/src/widget/Router.tsx
- Split `useKeepWalletStateSynced` part of `useGetAccount` logic and moved it to a separate hook
- Removed other places we update source wallet, and just rely on `useKeepWalletStateSynced`
- Stop using `useQuery` for `useAutoSetAddresses`, instead only call `connectRequiredChains()` when connected wallets have changed
https://github.com/user-attachments/assets/f599219f-83d3-4a65-99b0-d5ee222ef740
=> fix ability for recovery addresses to be auto updated when wallet is changed

.changeset/forty-spiders-notice.md, packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailed.tsx
Updated svg swapVenueOrBridge to be the color of the main text using technique found here -> https://jsfiddle.net/KuhlTime/2j8exgcb/
=> render swapVenueOrBridge svg differently so they can use theme color

.changeset/wise-comics-watch.md, packages/widget/src/pages/ErrorPage/ErrorPage.tsx, packages/widget/src/pages/ErrorPage/ErrorPageBadPriceWarning.tsx, packages/widget/src/pages/ErrorPage/ErrorPageLowInfoWarning.tsx, packages/widget/src/pages/SwapPage/SwapPage.tsx, packages/widget/src/state/errorPage.ts
renamed "trade warning" to "bad price warning"
=> [FRE-1543] read and add a low info warning to the widget

.changeset/purple-tools-do.md, packages/widget/src/components/Modal.tsx, packages/widget/src/pages/SwapPage/SwapPageBridge.tsx, packages/widget/src/state/route.ts
Fix edge case with locked assets
- Disable ability to swap source/dest assets if one of them is locked
- Fix bug where once an asset is locked, even if you stop passing srcLocked/destLocked it remains locked (due to localStorage)
=> Fix locked assets

docs/mint.json
This adds the GTM integration to the skip go docs.
=> docs: feat: Add Google Tag Manager tagId

.changeset/gorgeous-poems-count.md, packages/widget/src/hooks/useGetAssetDetails.tsx, packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailedRow.tsx
Update useGetAssetDetails to use case-insensitive search for denom/chainId
Add placeholder if there is no logo_uri
=> [FRE-579] Update useGetAssetDetails to use case-insensitive search for denom/chainId

.changeset/many-steaks-flow.md, packages/widget/src/utils/crypto.ts
Integers (numbers without a period or exponent notation) are accurate up to 15 digits.
=> [FRE-1568] problem with using max button for large precision numbers

packages/widget/__tests__/Widget.test.tsx, packages/widget/src/components/Modal.tsx, packages/widget/src/state/skipClient.ts, packages/widget/src/widget/Widget.tsx
This adds a completely optional `rootId` property to the `Widget` which will set an attribute to the modal roots and the Widget component. This allows for selecting, styling and querying the widget and its modals. Because modals are in portals it is impossible to find in a consistent manner; this PR fixes this issue.
In our case, when disabling the shadow DOM, there are styling issues that can be fixed with better CSS rules (e.g. `[data-root-id="skip-widget"] img { max-width: none !important; }` to solve some padding issues), and better handling of events bubbling using selectors to see if those events were created from within the widget and its modals (e.g. pressing "Escape" also closes our modal even though it shouldn't).
From here we can see if it's a modal (`body > [data-root-id]`) or …
=> Add a configuration that sets a "data-root-id" attr on all root elements

.changeset/chatty-seals-fail.md, packages/widget/src/pages/SwapPage/SwapPageAssetChainInput.tsx, packages/widget/src/utils/number.ts
Overview
This PR adds automatic text resizing for large numeric values in the widget's input fields. When a number exceeds 14 characters, the font size is automatically reduced to ensure it fits properly in the container without being cut off or overflowing.
Implementation Details
Added a new utility function shouldReduceFontSize() that determines when a number has too many characters
Implemented responsive font sizing in StyledInput component that applies smaller text only when needed
Used styled-component props for type-safe styling logic following codebase conventions
Applied proportional size reduction (38px → 30px on desktop, 30px → 24px on mobile)
=> [FRE-1506] Dynamic Font Size Reduction for Large Numbers

.changeset/nice-crews-yell.md, packages/widget/src/modals/SetAddressModal/SetAddressModal.tsx
Update manual address entry modal font-size and font-family
Figma/design:
=> Update manual address entry modal font size and font-family

.changeset/sweet-avocados-dress.md, packages/widget/src/components/Modal.tsx
https://developer.mozilla.org/en-US/docs/Web/CSS/animation-fill-mode
Pauses animation after it completes using `animation-fill-mode: forwards`
Fixes modal flickering by pausing the animation after it completes
Remove using timer to close the modal, instead close after animation completes with `onAnimationEnd`
=> [FRE-1646] Fix modal flickering

.changeset/old-crabs-develop.md, packages/widget/src/modals/ConnectedWalletModal/ConnectEcoRow.tsx, packages/widget/src/modals/ConnectedWalletModal/EcosystemConnectors.tsx
if ChainType is cosmos, show addresses in this order
1. address for sourceAsset
2. address for default of ecosystem (cosmoshub-4 / provider)
3. first address found in cosmosAccounts
Add default chainId for ecosystem as fallback if sourceAsset?.chainId is undefined when connecting wallet
=> Fix connect eco row

.changeset/eleven-ants-knock.md, packages/widget/src/pages/ErrorPage/ErrorPageBadPriceWarning.tsx, packages/widget/src/pages/SwapPage/SwapPage.tsx
Enhance ErrorPageBadPriceWarning component to handle USD values and p…rice impact warnings more effectively. Update SwapPage to rely solely on API warning type for bad price warnings.
=> [FRE-1641] Improve Bad Price Error Handling

.changeset/odd-tables-dress.md, packages/widget/src/state/swapExecutionPage.ts
Fix clearing validating when returning from user rejected request, Fix no longer showing user rejected request unless currently on swap execution page
=> Fix clearing validating when returning from user rejected request, Fix no longer showing user rejected request unless currently on swap execution page

.changeset/kind-eagles-collect.md, packages/client/src/private-functions/evm/executeEvmTransaction.ts, packages/client/src/private-functions/svm/executeSvmTransaction.ts
- remove unused ClientState signer fallbacks in EVM and SVM transaction helpers
- `npx tsc -b packages/client/tsconfig.json` *(fails: Cannot find modules)*
- `yarn test` *(fails: network access needed to download yarn)*
=> Fix signer fallback bug

docs/widget/getting-started.mdx
- fix typo in widget documentation (walk you through)
- `yarn test` *(fails: ConnectTimeoutError due to no network)*
=> Fix typo in widget docs

.changeset/twelve-shrimps-end.md, packages/client/src/private-functions/getRestEndpointForChain.ts
- correct error message in `getRestEndpointForChain`
- `yarn test` *(fails: yarn cannot download dependencies)*
=> Fix error text for REST endpoint lookup

.changeset/fix-window-check.md, packages/widget/src/hooks/useIsMobileScreenSize.ts
- avoid referencing `window` before checking existence in `useIsMobileScreenSize`
- add changeset
- `npm test` *(fails: connect EHOSTUNREACH)*
=> Fix mobile screen size check

.changeset/fix-mobile-date-format.md, AGENTS.md, packages/widget/__tests__/Keplr.test.tsx, packages/widget/src/utils/date.test.ts, packages/widget/src/utils/date.ts
- ensure mobile date formatting pads hours, minutes, month, and day with zeros
- add unit test demonstrating formatted output
- document in changeset
- `yarn test` *(fails to fetch packages)*
=> Pad Mobile Date Format

.changeset/add-clienttype-tests.md, packages/widget/src/utils/clientType.test.ts
- add unit tests for clientType utilities
- include changeset for widget package
- `yarn test-widget` *(fails: Error when performing the request to https://repo.yarnpkg.com...)*
=> Add clientType operation tests

.changeset/twenty-keys-tease.md, packages/widget/src/pages/SwapPage/SwapPageHeader.tsx, packages/widget/src/utils/migrateOldLocalStorageValues.ts
Fix infinite spinner for the history icon if the last transaction was a 2tx route but the second tx has not been signed
=> Fix infinite spinner in the history icon

docs/swagger.yml
- Add FeeBehavior enum with FEE_BEHAVIOR_DEDUCTED and FEE_BEHAVIOR_ADDITIONAL values
- Update Fee schema to include fee_behavior field referencing FeeBehavior enum
- Supports new fee behavior determination system from solve project
- FEE_BEHAVIOR_DEDUCTED: Fee subtracted from transfer amount 
- FEE_BEHAVIOR_ADDITIONAL: Fee charged on top of transfer amount
=> [API-3953] Add FeeBehavior enum and fee_behavior field to Fee schema

docs/client/getting-started.mdx
The documentation site has example route params that are not camelCase (ex: chainID instead of chainId) and it was showing typescript errors for me in development.
=> docs: camelCase for route params reflecting the typescript

docs/eureka/eureka-overview.mdx
Removes a broken link to a non-existent testnet testing guide from the Eureka documentation.
The Eureka overview page contains a step titled "Explore the Testnet" that links to `/eureka/testnet-testing-guide`, but this file no longer exists, resulting in a 404 error for users.
Removed the broken "Explore the Testnet" step from the Getting Started section. Users can still access all necessary Eureka integration information through the remaining documentation sections:
- Technical Overview
- Custom ERC20 Integration guide
- Contact information for integration support
- Integration Guide
Verified that the remaining links in the Eureka documentation are valid and functional.
=> Remove broken testnet testing guide link from Eureka documentation

.changeset/lucky-parents-decide.md, packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteDetailedRow.tsx, packages/widget/src/pages/SwapExecutionPage/SwapExecutionPageRouteSimpleRow.tsx
=> Avoid showing loading animation instead of wallet icon for manual address input

.changeset/fast-plums-worry.md, examples/client/index.ts, packages/client/src/public-functions/setApiOptions.ts, packages/client/src/public-functions/setClientOptions.ts, packages/client/src/state/apiState.ts, packages/client/src/utils/generateApi.ts
=> Allow calling api functions without first configuring api/client options

docs/docs.json, docs/release-notes/client.mdx, docs/release-notes/widget.mdx, docs/widget/gas-on-receive.mdx
- Add comprehensive documentation for the Gas on Receive feature at `docs/widget/gas-on-receive.mdx`
- Update widget and client library release notes with feature descriptions and documentation links
- Add gas-on-receive page to navigation in `docs.json` for easy discovery
- Include working code examples for both widget (auto-detection + user toggle) and client library (manual setup)
- Complete feature overview and how it works
- Supported/not supported chains with clear rationale
- Default gas amounts: $0.10 (Cosmos), $2.00 (EVM L2s)
- Widget behavior: auto-detects need, user toggles feature on/off
- Client library usage with `executeMultipleRoutes` function and proper API examples
- Balance checking logic with correct threshold calculations
- Error handling and troubleshooting guidance …
=> [CSE-207] Add Gas on Receive documentation

.changeset/proud-snails-arrive.md, docs/swagger.yml, packages/client/src/types/swaggerTypes.ts, packages/client/src/types/swaggerTypesJson.ts
Adds `HIGH_LOSS_WARNING` and `HIGH_LOSS_ERROR` to the Swagger specification to support the new high loss protection feature.
- Added `HIGH_LOSS_WARNING` enum value
- Added description: "The route would result in a USD loss exceeding the configured threshold"
- Added `HIGH_LOSS_ERROR` enum value
- Added description: "The route would result in a USD loss exceeding the configured threshold and has been blocked"
- Verified enum additions are syntactically correct
- Changes are additive and non-breaking
=> [API-4572] feat: Add HIGH_LOSS_WARNING and HIGH_LOSS_ERROR to Swagger spec

apps/explorer/src/app/page.tsx, apps/explorer/src/components/TokenDetails.tsx, apps/explorer/src/components/TransactionDetails.tsx, packages/widget/src/components/Tooltip.tsx
show view token details if transferAssetRelease data exists
update tooltips to ignore overflow of parent (using react portal)
old:
new:
=> update tooltips to use react portal and show view token details if transferAssetRelease data exists for simple view

apps/explorer/src/app/page.tsx
the first time a tx returns "tx not found" it will automatically call retry_track and fetch the status again before rendering anything, subsequent calls will not call retry_track
=> Auto retry_track transactions once when error.message === "tx not found"

.changeset/full-ears-juggle.md, packages/widget/src/utils/number.ts
confirmed that 
```
formatDisplayAmount(999_999, {
decimals: 2,
});
formatDisplayAmount(1_000_000, {
decimals: 2,
});
```
are now both = 1M
and 
```
formatDisplayAmount(999.999, {
decimals: 2,
}),
formatDisplayAmount(1000, {
decimals: 2,
}),
```
are now both = 1k
=> Fix formatDisplayAmount logic
